### ISSUE TITLE
Display the rules in an extra menu in the app

### ISSUE THREAD

**Issue by haepeto** [CoolestProjectsBelgium/coolestproject#4]
As a participant, I want to be able to consult the rules again after registration. 
Add additional page (next to Project and User) to the menu to display the rules (again). The rules and their translations have to be exactly the same as on the Index page.

**Comment by MWoidt** [comment]
In the registration page at the very end you have a link which opens the rules page in a second tab. you can leave after reading and you are back in your project or user view.
We can take this link to put it beside the Login button and inside Project and User. 
By this we do not need the content of the rules again but can resuse this. **Is programmed in the registration.vue****

Registration page:
O Lees zeker onze regels. Ga je akkoord?
"Je moet akkoord gaan met volgende vraag om je te kunnen registreren"   -> https://app.coolestprojects.be/ opens a 2nd tab with the rules.

**Comment by MWoidt** [comment]
done
